//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace C2InfoSys.Schedule {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="c2infosys.com/Common/BusinessCalendar.xsd", IsNullable=false)]
    public partial class BusinessCalendar {
        
        private Year[] yearField;
        
        private string codeField;
        
        private string descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Year")]
        public Year[] Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public partial class Year {
        
        private Month[] monthField;
        
        private int noField;
        
        private YesNo leapYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Month")]
        public Month[] Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo LeapYear {
            get {
                return this.leapYearField;
            }
            set {
                this.leapYearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public partial class Month {
        
        private Day[] dayField;
        
        private int noField;
        
        private string nameField;

        private string abrevField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Day")]
        public Day[] Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Abrev {
            get {
                return this.abrevField;
            }
            set {
                this.abrevField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public partial class Day {
        
        private int yearDayField;
        
        private int monthDayField;
        
        private int weekDayField;

        private YesNo businessDayField;

        private string nameField;

        private string abrevField;

        private Quarter quarterStartField;
        
        private bool quarterStartFieldSpecified;

        private Quarter quarterEndField;
        
        private bool quarterEndFieldSpecified;

        private YesNo yearEndField;
        
        private bool yearEndFieldSpecified;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int YearDay {
            get {
                return this.yearDayField;
            }
            set {
                this.yearDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MonthDay {
            get {
                return this.monthDayField;
            }
            set {
                this.monthDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int WeekDay {
            get {
                return this.weekDayField;
            }
            set {
                this.weekDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo BusinessDay {
            get {
                return this.businessDayField;
            }
            set {
                this.businessDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Abrev {
            get {
                return this.abrevField;
            }
            set {
                this.abrevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Quarter QuarterStart {
            get {
                return this.quarterStartField;
            }
            set {
                this.quarterStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuarterStartSpecified {
            get {
                return this.quarterStartFieldSpecified;
            }
            set {
                this.quarterStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Quarter QuarterEnd {
            get {
                return this.quarterEndField;
            }
            set {
                this.quarterEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuarterEndSpecified {
            get {
                return this.quarterEndFieldSpecified;
            }
            set {
                this.quarterEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo YearEnd {
            get {
                return this.yearEndField;
            }
            set {
                this.yearEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearEndSpecified {
            get {
                return this.yearEndFieldSpecified;
            }
            set {
                this.yearEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }   

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public enum DayName {
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
        
        /// <remarks/>
        Sunday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public enum DayAbrev {
        
        /// <remarks/>
        Mon,
        
        /// <remarks/>
        Tue,
        
        /// <remarks/>
        Wed,
        
        /// <remarks/>
        Thu,
        
        /// <remarks/>
        Fri,
        
        /// <remarks/>
        Sat,
        
        /// <remarks/>
        Sun,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public enum Quarter {
        
        /// <remarks/>
        Q1,
        
        /// <remarks/>
        Q2,
        
        /// <remarks/>
        Q3,
        
        /// <remarks/>
        Q4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public enum MonthName {
        
        /// <remarks/>
        January,
        
        /// <remarks/>
        February,
        
        /// <remarks/>
        March,
        
        /// <remarks/>
        April,
        
        /// <remarks/>
        May,
        
        /// <remarks/>
        June,
        
        /// <remarks/>
        July,
        
        /// <remarks/>
        August,
        
        /// <remarks/>
        September,
        
        /// <remarks/>
        October,
        
        /// <remarks/>
        November,
        
        /// <remarks/>
        December,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public enum MonthAbrev {
        
        /// <remarks/>
        Jan,
        
        /// <remarks/>
        Feb,
        
        /// <remarks/>
        Mar,
        
        /// <remarks/>
        Apr,
        
        /// <remarks/>
        May,
        
        /// <remarks/>
        Jun,
        
        /// <remarks/>
        Jul,
        
        /// <remarks/>
        Aug,
        
        /// <remarks/>
        Sep,
        
        /// <remarks/>
        Oct,
        
        /// <remarks/>
        Nov,
        
        /// <remarks/>
        Dec,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="c2infosys.com/Common/BusinessCalendar.xsd")]
    public enum YesNo {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
}
