//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace C2InfoSys.FileIntegratrex.Lib {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Integrations", Namespace = "c2infosys.com/Integratrex/Service.Config.xsd", IsNullable = false)]
    public partial class XIntegrations {

        private XIntegration[] integrationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Integration")]
        public XIntegration[] Integration {
            get {
                return this.integrationField;
            }
            set {
                this.integrationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XIntegration {

        private XSchedule scheduleField;

        private XSource sourceField;

        private XOnContact onContactField;

        private XPattern[] patternsField;

        private XResponse[] responsesField;

        private XLog logField;

        private string descField;

        private XIntegrationEnable enableField;

        /// <remarks/>
        public XSchedule Schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
            }
        }

        /// <remarks/>
        public XSource Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        public XOnContact OnContact {
            get {
                return this.onContactField;
            }
            set {
                this.onContactField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Pattern", IsNullable = false)]
        public XPattern[] Patterns {
            get {
                return this.patternsField;
            }
            set {
                this.patternsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", IsNullable = false)]
        public XResponse[] Responses {
            get {
                return this.responsesField;
            }
            set {
                this.responsesField = value;
            }
        }

        /// <remarks/>
        public XLog Log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XIntegrationEnable Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XSchedule {

        private XContinuous continuousField;

        private XCalendar[] calendarField;

        /// <remarks/>
        public XContinuous Continuous {
            get {
                return this.continuousField;
            }
            set {
                this.continuousField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Calendar")]
        public XCalendar[] Calendar {
            get {
                return this.calendarField;
            }
            set {
                this.calendarField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XContinuous {

        private string intervalField;

        private string dailyResponseLimitField;

        private string businessCalendarField;

        private XContinuousBusinessDay businessDayField;

        public XContinuous() {
            this.businessDayField = XContinuousBusinessDay.N;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string Interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string DailyResponseLimit {
            get {
                return this.dailyResponseLimitField;
            }
            set {
                this.dailyResponseLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BusinessCalendar {
            get {
                return this.businessCalendarField;
            }
            set {
                this.businessCalendarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(XContinuousBusinessDay.N)]
        public XContinuousBusinessDay BusinessDay {
            get {
                return this.businessDayField;
            }
            set {
                this.businessDayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XContinuousBusinessDay {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("N/A")]
        NA,

        /// <remarks/>
        Y,

        /// <remarks/>
        N,

        /// <remarks/>
        Prior,

        /// <remarks/>
        Next,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XEmailLog {

        private string subjectField;

        private string toField;

        private string ccField;

        private string bCCField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CC {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BCC {
            get {
                return this.bCCField;
            }
            set {
                this.bCCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XLog {

        private XEmailLog emailField;

        private XLogLevel levelField;

        private bool levelFieldSpecified;

        private XLogEnable enableField;

        /// <remarks/>
        public XEmailLog Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XLogLevel Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LevelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XLogEnable Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XLogLevel {

        /// <remarks/>
        Critical,

        /// <remarks/>
        Error,

        /// <remarks/>
        Warning,

        /// <remarks/>
        Information,

        /// <remarks/>
        Verbose,

        /// <remarks/>
        Start,

        /// <remarks/>
        Stop,

        /// <remarks/>
        Suspend,

        /// <remarks/>
        Resume,

        /// <remarks/>
        Transfer,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XLogEnable {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XParameter {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XDatabaseTgt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XPowerShellTgt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XProgramTgt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XEmailTgt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XSFTPTgt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XFTPTgt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XWebTgt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XNetworkTgt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XLocalTgt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XTargetLocation {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XDatabaseTgt : XTargetLocation {

        private XCredentials credentialsField;

        private XParameter[] parametersField;

        private XDatabaseTgtDBMS dBMSField;

        private string serverField;

        private string dbField;

        private string queryField;

        private XDatabaseTgtAction actionField;

        /// <remarks/>
        public XCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable = false)]
        public XParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XDatabaseTgtDBMS DBMS {
            get {
                return this.dBMSField;
            }
            set {
                this.dBMSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Db {
            get {
                return this.dbField;
            }
            set {
                this.dbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XDatabaseTgtAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XCredentials {

        private string userField;

        private string passwordField;

        private XCredentialsEncrypted encryptedField;

        private bool encryptedFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XCredentialsEncrypted Encrypted {
            get {
                return this.encryptedField;
            }
            set {
                this.encryptedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EncryptedSpecified {
            get {
                return this.encryptedFieldSpecified;
            }
            set {
                this.encryptedFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XCredentialsEncrypted {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XDatabaseTgtDBMS {

        /// <remarks/>
        SQLServer,

        /// <remarks/>
        Oracle,

        /// <remarks/>
        MySQL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XDatabaseTgtAction {

        /// <remarks/>
        None,

        /// <remarks/>
        StoredProcedure,

        /// <remarks/>
        Query,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XPowerShellTgt : XTargetLocation {

        private XParameter[] parametersField;

        private string[] textField;

        private string directoryField;

        private string pathField;

        private string scriptField;

        private string argsField;

        private XPowerShellTgtAction actionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable = false)]
        public XParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Directory {
            get {
                return this.directoryField;
            }
            set {
                this.directoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Args {
            get {
                return this.argsField;
            }
            set {
                this.argsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XPowerShellTgtAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XPowerShellTgtAction {

        /// <remarks/>
        None,

        /// <remarks/>
        Run,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XProgramTgt : XTargetLocation {

        private XParameter[] parametersField;

        private string pathField;

        private string argsField;

        private XProgramTgtAction actionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable = false)]
        public XParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Args {
            get {
                return this.argsField;
            }
            set {
                this.argsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XProgramTgtAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XProgramTgtAction {

        /// <remarks/>
        None,

        /// <remarks/>
        Execute,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XEmailTgt : XTargetLocation {

        private string subjectField;

        private string mailFromField;

        private string toField;

        private string ccField;

        private string bCCField;

        private XEmailTgtAction actionField;

        private string[] textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MailFrom {
            get {
                return this.mailFromField;
            }
            set {
                this.mailFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CC {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BCC {
            get {
                return this.bCCField;
            }
            set {
                this.bCCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XEmailTgtAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XEmailTgtAction {

        /// <remarks/>
        None,

        /// <remarks/>
        Notify,

        /// <remarks/>
        Attach,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XSFTPTgt : XTargetLocation {

        private XURI uRIField;

        private XCredentials credentialsField;

        private XSFTPTgtAction actionField;

        private XSFTPTgtOverwrite overwriteField;

        private XSFTPTgtCreateDirectory createDirectoryField;

        /// <remarks/>
        public XURI URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }

        /// <remarks/>
        public XCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XSFTPTgtAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XSFTPTgtOverwrite Overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XSFTPTgtCreateDirectory CreateDirectory {
            get {
                return this.createDirectoryField;
            }
            set {
                this.createDirectoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XURI {

        private string portField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XSFTPTgtAction {

        /// <remarks/>
        None,

        /// <remarks/>
        Upload,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XSFTPTgtOverwrite {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XSFTPTgtCreateDirectory {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XFTPTgt : XTargetLocation {

        private XURI uRIField;

        private XCredentials credentialsField;

        private XFTPTgtAction actionField;

        private XFTPTgtOverwrite overwriteField;

        private XFTPTgtCreateDirectory createDirectoryField;

        /// <remarks/>
        public XURI URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }

        /// <remarks/>
        public XCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XFTPTgtAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XFTPTgtOverwrite Overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XFTPTgtCreateDirectory CreateDirectory {
            get {
                return this.createDirectoryField;
            }
            set {
                this.createDirectoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XFTPTgtAction {

        /// <remarks/>
        None,

        /// <remarks/>
        Upload,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XFTPTgtOverwrite {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XFTPTgtCreateDirectory {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XWebTgt : XTargetLocation {

        private XURI uRIField;

        private XCredentials credentialsField;

        /// <remarks/>
        public XURI URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }

        /// <remarks/>
        public XCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XNetworkTgt : XTargetLocation {

        private XPath pathField;

        private XNetworkTgtAction actionField;

        private XNetworkTgtOverwrite overwriteField;

        private XNetworkTgtCreateDirectory createDirectoryField;

        /// <remarks/>
        public XPath Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XNetworkTgtAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XNetworkTgtOverwrite Overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XNetworkTgtCreateDirectory CreateDirectory {
            get {
                return this.createDirectoryField;
            }
            set {
                this.createDirectoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XPath {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XNetworkTgtAction {

        /// <remarks/>
        None,

        /// <remarks/>
        Copy,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XNetworkTgtOverwrite {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XNetworkTgtCreateDirectory {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XLocalTgt : XTargetLocation {

        private XPath pathField;

        private XLocalTgtAction actionField;

        private XLocalTgtOverwrite overwriteField;

        private XLocalTgtCreateDirectory createDirectoryField;

        /// <remarks/>
        public XPath Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XLocalTgtAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XLocalTgtOverwrite Overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XLocalTgtCreateDirectory CreateDirectory {
            get {
                return this.createDirectoryField;
            }
            set {
                this.createDirectoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XLocalTgtAction {

        /// <remarks/>
        None,

        /// <remarks/>
        Copy,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XLocalTgtOverwrite {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XLocalTgtCreateDirectory {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XTarget {

        private XTargetLocation itemField;

        private string descField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Database", typeof(XDatabaseTgt))]
        [System.Xml.Serialization.XmlElementAttribute("Email", typeof(XEmailTgt))]
        [System.Xml.Serialization.XmlElementAttribute("FTP", typeof(XFTPTgt))]
        [System.Xml.Serialization.XmlElementAttribute("Local", typeof(XLocalTgt))]
        [System.Xml.Serialization.XmlElementAttribute("Network", typeof(XNetworkTgt))]
        [System.Xml.Serialization.XmlElementAttribute("PowerShell", typeof(XPowerShellTgt))]
        [System.Xml.Serialization.XmlElementAttribute("Program", typeof(XProgramTgt))]
        [System.Xml.Serialization.XmlElementAttribute("SFTP", typeof(XSFTPTgt))]
        public XTargetLocation Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XDecompress {

        private XDecompressType typeField;

        private XDecompressCompressionLevel compressionLevelField;

        private bool compressionLevelFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XDecompressType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XDecompressCompressionLevel CompressionLevel {
            get {
                return this.compressionLevelField;
            }
            set {
                this.compressionLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompressionLevelSpecified {
            get {
                return this.compressionLevelFieldSpecified;
            }
            set {
                this.compressionLevelFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XDecompressType {

        /// <remarks/>
        ZIP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XDecompressCompressionLevel {

        /// <remarks/>
        Fastest,

        /// <remarks/>
        NoCompression,

        /// <remarks/>
        Optimal,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XCompress {

        private XCompressType typeField;

        private XCompressCompressionLevel compressionLevelField;

        private bool compressionLevelFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XCompressType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XCompressCompressionLevel CompressionLevel {
            get {
                return this.compressionLevelField;
            }
            set {
                this.compressionLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompressionLevelSpecified {
            get {
                return this.compressionLevelFieldSpecified;
            }
            set {
                this.compressionLevelFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XCompressType {

        /// <remarks/>
        ZIP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XCompressCompressionLevel {

        /// <remarks/>
        Fastest,

        /// <remarks/>
        NoCompression,

        /// <remarks/>
        Optimal,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XCompression {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Compress", typeof(XCompress))]
        [System.Xml.Serialization.XmlElementAttribute("Decompress", typeof(XDecompress))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XTextFile {

        private XTextFileOriginalEncoding originalEncodingField;

        private bool originalEncodingFieldSpecified;

        private XTextFileTargetEncoding targetEncodingField;

        private bool targetEncodingFieldSpecified;

        private XTextFileLineBreaks lineBreaksField;

        private bool lineBreaksFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XTextFileOriginalEncoding OriginalEncoding {
            get {
                return this.originalEncodingField;
            }
            set {
                this.originalEncodingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OriginalEncodingSpecified {
            get {
                return this.originalEncodingFieldSpecified;
            }
            set {
                this.originalEncodingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XTextFileTargetEncoding TargetEncoding {
            get {
                return this.targetEncodingField;
            }
            set {
                this.targetEncodingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TargetEncodingSpecified {
            get {
                return this.targetEncodingFieldSpecified;
            }
            set {
                this.targetEncodingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XTextFileLineBreaks LineBreaks {
            get {
                return this.lineBreaksField;
            }
            set {
                this.lineBreaksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineBreaksSpecified {
            get {
                return this.lineBreaksFieldSpecified;
            }
            set {
                this.lineBreaksFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XTextFileOriginalEncoding {

        /// <remarks/>
        ASCII,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UTF-7")]
        UTF7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UTF-8")]
        UTF8,

        /// <remarks/>
        Unicode,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UTF-32")]
        UTF32,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XTextFileTargetEncoding {

        /// <remarks/>
        ASCII,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UTF-7")]
        UTF7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UTF-8")]
        UTF8,

        /// <remarks/>
        Unicode,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UTF-32")]
        UTF32,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XTextFileLineBreaks {

        /// <remarks/>
        crlf,

        /// <remarks/>
        cr,

        /// <remarks/>
        lf,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XTransform {

        private XTextFile textFileField;

        private XCompression compressionField;

        /// <remarks/>
        public XTextFile TextFile {
            get {
                return this.textFileField;
            }
            set {
                this.textFileField = value;
            }
        }

        /// <remarks/>
        public XCompression Compression {
            get {
                return this.compressionField;
            }
            set {
                this.compressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XRenameResponse {

        private XRenameResponseEnable enableField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XRenameResponseEnable Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XRenameResponseEnable {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XResponse {

        private XRenameResponse renameField;

        private XTransform transformField;

        private XTarget targetField;

        private string descField;

        private XResponseEnable enableField;

        /// <remarks/>
        public XRenameResponse Rename {
            get {
                return this.renameField;
            }
            set {
                this.renameField = value;
            }
        }

        /// <remarks/>
        public XTransform Transform {
            get {
                return this.transformField;
            }
            set {
                this.transformField = value;
            }
        }

        /// <remarks/>
        public XTarget Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XResponseEnable Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XResponseEnable {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XPattern {

        private string descField;

        private XPatternType typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XPatternType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XPatternType {

        /// <remarks/>
        RegEx,

        /// <remarks/>
        Simple,

        /// <remarks/>
        Exact,

        /// <remarks/>
        ExactIgnoreCase,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XRenameOnContact {

        private XRenameOnContactOriginal originalField;

        private XRenameOnContactWorkingCopy workingCopyField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XRenameOnContactOriginal Original {
            get {
                return this.originalField;
            }
            set {
                this.originalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XRenameOnContactWorkingCopy WorkingCopy {
            get {
                return this.workingCopyField;
            }
            set {
                this.workingCopyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XRenameOnContactOriginal {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XRenameOnContactWorkingCopy {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XMatchBy {

        private XMatchByFileName fileNameField;

        private XMatchByFileSize fileSizeField;

        private XMatchByLastModifiedDate lastModifiedDateField;

        private XMatchByMD5 mD5Field;

        private XMatchBySHA1 sHA1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XMatchByFileName FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XMatchByFileSize FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XMatchByLastModifiedDate LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XMatchByMD5 MD5 {
            get {
                return this.mD5Field;
            }
            set {
                this.mD5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XMatchBySHA1 SHA1 {
            get {
                return this.sHA1Field;
            }
            set {
                this.sHA1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XMatchByFileName {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XMatchByFileSize {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XMatchByLastModifiedDate {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XMatchByMD5 {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XMatchBySHA1 {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XSupressDuplicates {

        private XMatchBy matchByField;

        private XSupressDuplicatesEnable enableField;

        /// <remarks/>
        public XMatchBy MatchBy {
            get {
                return this.matchByField;
            }
            set {
                this.matchByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XSupressDuplicatesEnable Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XSupressDuplicatesEnable {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XOnContact {

        private XSupressDuplicates supressDuplicatesField;

        private XRenameOnContact renameField;

        private XOnContactMoveToWorkingArea moveToWorkingAreaField;

        private XOnContactDeleteFromSource deleteFromSourceField;

        private XOnContactStoreFileInfo storeFileInfoField;

        private XOnContactCalculateMD5 calculateMD5Field;

        private XOnContactCalculateSHA1 calculateSHA1Field;

        /// <remarks/>
        public XSupressDuplicates SupressDuplicates {
            get {
                return this.supressDuplicatesField;
            }
            set {
                this.supressDuplicatesField = value;
            }
        }

        /// <remarks/>
        public XRenameOnContact Rename {
            get {
                return this.renameField;
            }
            set {
                this.renameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XOnContactMoveToWorkingArea MoveToWorkingArea {
            get {
                return this.moveToWorkingAreaField;
            }
            set {
                this.moveToWorkingAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XOnContactDeleteFromSource DeleteFromSource {
            get {
                return this.deleteFromSourceField;
            }
            set {
                this.deleteFromSourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XOnContactStoreFileInfo StoreFileInfo {
            get {
                return this.storeFileInfoField;
            }
            set {
                this.storeFileInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XOnContactCalculateMD5 CalculateMD5 {
            get {
                return this.calculateMD5Field;
            }
            set {
                this.calculateMD5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XOnContactCalculateSHA1 CalculateSHA1 {
            get {
                return this.calculateSHA1Field;
            }
            set {
                this.calculateSHA1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XOnContactMoveToWorkingArea {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XOnContactDeleteFromSource {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XOnContactStoreFileInfo {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XOnContactCalculateMD5 {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XOnContactCalculateSHA1 {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XSFTPSrc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XFTPSrc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XWebSrc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XNetworkSrc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XLocalSrc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XSourceLocation {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XSFTPSrc : XSourceLocation {

        private XURI uRIField;

        private XCredentials credentialsField;

        /// <remarks/>
        public XURI URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }

        /// <remarks/>
        public XCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XFTPSrc : XSourceLocation {

        private XURI uRIField;

        private XCredentials credentialsField;

        /// <remarks/>
        public XURI URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }

        /// <remarks/>
        public XCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XWebSrc : XSourceLocation {

        private XURI uRIField;

        private XCredentials credentialsField;

        /// <remarks/>
        public XURI URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }

        /// <remarks/>
        public XCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XNetworkSrc : XSourceLocation {

        private XPath pathField;

        /// <remarks/>
        public XPath Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XLocalSrc : XSourceLocation {

        private XPath pathField;

        /// <remarks/>
        public XPath Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XSource {

        private XSourceLocation itemField;

        private string descField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FTP", typeof(XFTPSrc))]
        [System.Xml.Serialization.XmlElementAttribute("Local", typeof(XLocalSrc))]
        [System.Xml.Serialization.XmlElementAttribute("Network", typeof(XNetworkSrc))]
        [System.Xml.Serialization.XmlElementAttribute("SFTP", typeof(XSFTPSrc))]
        [System.Xml.Serialization.XmlElementAttribute("Web", typeof(XWebSrc))]
        public XSourceLocation Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public partial class XCalendar {

        private XCalendarOccurs occursField;

        private XCalendarBusinessDay businessDayField;

        private string businessCalendarField;

        private string offsetField;

        private string timeOfDayField;

        public XCalendar() {
            this.businessDayField = XCalendarBusinessDay.N;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public XCalendarOccurs Occurs {
            get {
                return this.occursField;
            }
            set {
                this.occursField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(XCalendarBusinessDay.N)]
        public XCalendarBusinessDay BusinessDay {
            get {
                return this.businessDayField;
            }
            set {
                this.businessDayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BusinessCalendar {
            get {
                return this.businessCalendarField;
            }
            set {
                this.businessCalendarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeOfDay {
            get {
                return this.timeOfDayField;
            }
            set {
                this.timeOfDayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XCalendarOccurs {

        /// <remarks/>
        Second,

        /// <remarks/>
        Minute,

        /// <remarks/>
        Hour,

        /// <remarks/>
        Day,

        /// <remarks/>
        Week,

        /// <remarks/>
        Month,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XCalendarBusinessDay {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "c2infosys.com/Integratrex/Service.Config.xsd")]
    public enum XIntegrationEnable {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }
}
